INSTRUCTIONS: Going back to our table in the activity aove, try transforming the data by handling the missing values. Since all the data are numebric, no encoding of categorical data is needed. You try also applying feature scaling using both normalization and standardization techniques. Print out the values to see the effects of these preprocessing techniques.

# Importing necessary packages

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset

In [4]:
#import the dataset using .read_csv
dataset = pd.read_csv('Data.csv')
dataset

Grill temp. (Fahreinheit)  Weight of beef patty (lb)  \
0                        NaN                       0.33   
1                        NaN                       0.24   
2                      550.0                        NaN   
3                      725.0                       0.45   
4                      600.0                        NaN   
5                      625.0                        NaN   
6                        NaN                       0.49   

   Burger rating (out of 10)  
0                        8.2  
1                        5.6  
2                        7.8  
3                        9.4  
4                        8.2  
5                        6.8  
6                        4.2

In [5]:
#locate the rows and columns of the input set
X = dataset.iloc[:, :-1].values

#locate the rows of the output set or the last columns
y = dataset.iloc[:, -1].values

In [6]:
#print the contents of X
print(X)

[[     nan 3.30e-01]
 [     nan 2.40e-01]
 [5.50e+02      nan]
 [7.25e+02 4.50e-01]
 [6.00e+02      nan]
 [6.25e+02      nan]
 [     nan 4.90e-01]]


In [7]:
#print the contents of y
print(y)

[8.2 5.6 7.8 9.4 8.2 6.8 4.2]


# Handling of the missing data

In [8]:
#import the package responsible for giving a theoretical value to an unknown one
from sklearn.impute import SimpleImputer

#decide which imputing strategy to use 
#first parameter means to replace all missing values
imputer = SimpleImputer(missing_values=np.nan, strategy = 'mean')
imputer.fit(X)

#impute all the missing data in the dataset
#no specifications since we don't have any strings in the dataset
X = imputer.transform(X)

In [9]:
#print the new imputed dataset
print(X)

[[6.250e+02 3.300e-01]
 [6.250e+02 2.400e-01]
 [5.500e+02 3.775e-01]
 [7.250e+02 4.500e-01]
 [6.000e+02 3.775e-01]
 [6.250e+02 3.775e-01]
 [6.250e+02 4.900e-01]]


# Feature Scaling

In [10]:
#split the data into sets
from sklearn.model_selection import train_test_split

#test_size = 0.2 is like we leave out 20% of the dataset for the testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)
X_train2, X_test2, y_train2, y_test2 = train_test_split(X, y, test_size = 0.2, random_state = 1)

print(X_train)

[[6.250e+02 2.400e-01]
 [6.250e+02 3.300e-01]
 [6.000e+02 3.775e-01]
 [7.250e+02 4.500e-01]
 [6.250e+02 3.775e-01]]


In [11]:
#applying standardization on dataset
#import the necessary tools
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

#values will be according to the input values
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [17]:
#applying normalization on dataset
#import the necessary tools
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

#fit computes the minimum and maximum for later scaling
#transform means to scale the features of X according to feature range
X_train2 = scaler.fit_transform(X_train2)
X_test2 = scaler.transform(X_test2)

# Results

In [18]:
#print the results for standardization
print(X_train)

[[-0.3441236  -1.6637861 ]
 [-0.3441236  -0.36169263]
 [-0.91766294  0.32552337]
 [ 1.95003374  1.374432  ]
 [-0.3441236   0.32552337]]


In [19]:
print(X_test)

[[-0.3441236   1.95314021]
 [-2.0647416   0.32552337]]


In [20]:
#print the results for normalization
print(X_train2)

[[0.2        0.        ]
 [0.2        0.42857143]
 [0.         0.6547619 ]
 [1.         1.        ]
 [0.2        0.6547619 ]]


In [21]:
print(X_test2)

[[ 0.2         1.19047619]
 [-0.4         0.6547619 ]]
